# -*- coding: utf-8 -*-
"""AlunoMedia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uTC_27OEkkE7xPlzZ0MbNbk3bzWaPpob
"""

aluno = input('digite o nome do aluno: ')
n1 = float(input('digite a primeira nota: '))
n2 = float(input('digite a segunda nota: '))
n3 = float(input('digite a terceira nota: '))
media = (n1+n2+n3)/3
if media >= 7:
    situacao = 'aprovado'
elif media >= 4:
    situacao = 'em recuperção'
else:
    situacao = 'reprovado'
print(f'O aluno {aluno} está em situação {situacao} com média {media} ')